# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.us.core
canonical: 'http://hl7.org/fhir/us/core'
name: USCore
title: US Core Implementation Guide
status: active
publisher:
  name: HL7 International - US Realm Steering Committee
  url: 'http://www.hl7.org/Special/committees/usrealm/index.cfm'
jurisdiction: 'urn:iso:std:iso:3166#US'
copyright: >-
  Used by permission of HL7 International, all rights reserved Creative Commons License
description: >-
  The US Core Implementation Guide is based on FHIR Version R4 and defines the minimum conformance requirements for accessing patient data. The Argonaut pilot implementations, ONC 2015 Edition Common Clinical Data Set (CCDS), and ONC U.S. Core Data for Interoperability (USCDI) v1 provided the requirements for this guide. The prior Argonaut search and vocabulary requirements, based on FHIR DSTU2, are updated in this guide to support FHIR Version R4. This guide was used as the basis for further testing and guidance by the Argonaut Project Team to provide additional content and guidance specific to Data Query Access for purpose of ONC Certification testing. These profiles are the foundation for future US Realm FHIR implementation guides. In addition to Argonaut, they are used by DAF-Research, QI-Core, and CIMI. Under the guidance of HL7 and the HL7 US Realm Steering Committee, the content will expand in future versions to meet the needs specific to the US Realm.

  These requirements were originally developed, balloted, and published in FHIR DSTU2 as part of the Office of the National Coordinator for Health Information Technology (ONC) sponsored Data Access Framework (DAF) project. For more information on how DAF became US Core see the US Core change notes.
license: CC0-1.0
date: 2020-10-10
version: 3.2.0
fhirVersion: 4.0.1
parameters:
  path-resource:
    - input/resources
    - fsh-generated/resources
  path-pages:
    - input/pagecontent
    - fsh-generated/includes
  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'
  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'true'
  excludexml: 'true'
  excludejsn: 'false'
  excludettl: 'true'
  excludemap: 'true'
  excludeexample: 'true'
  generate:
    - xml
    - json
copyrightyear: '2020+'
releaselabel: CI Build

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided ig-data/input/includes/menu.xml file, delete the "menu" property below.     │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Guidance: #guidance.html
      General Guidance: general-guidance.html
      Clinical Notes Guidance: clinical-notes-guidance.html
      Medication List Guidance: all-meds.html
      Basic Provenance: basic-provenance.html
      DSTU2 to R4 Conversion: r2-r4-guidance.html
      Future of US Core: future-of-us-core.html
  FHIR Artifacts: #artifact.html
      Profiles and Extensions: profiles.html
      Search Parameters and Operations: searchparameters.html
      Terminology: terminology.html
      Capability Statements: capstatements.html
  Security: security.html
  Examples: examples.html
  Downloads: downloads.html
