# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.us.core
canonical: 'http://hl7.org/fhir/us/core'
name: USCore
title: US Core Implementation Guide
status: active
publisher:
  name: HL7 International - Cross-Group Projects
  url: 'http://www.hl7.org/Special/committees/cgp'
  email: cgp@lists.HL7.org
jurisdiction: 'urn:iso:std:iso:3166#US'
copyright: >-
  Used by permission of HL7 International, all rights reserved Creative Commons License
description: >-
  The US Core Implementation Guide is based on FHIR Version R4 and defines the minimum conformance requirements for accessing patient data. The Argonaut pilot implementations, ONC 2015 Edition Common Clinical Data Set (CCDS), and ONC U.S. Core Data for Interoperability (USCDI) v1 provided the requirements for this guide. The prior Argonaut search and vocabulary requirements, based on FHIR DSTU2, are updated in this guide to support FHIR Version R4. This guide was used as the basis for further testing and guidance by the Argonaut Project Team to provide additional content and guidance specific to Data Query Access for purpose of ONC Certification testing. These profiles are the foundation for future US Realm FHIR implementation guides. In addition to Argonaut, they are used by DAF-Research, QI-Core, and CIMI. Under the guidance of HL7 and the HL7 US Realm Steering Committee, the content will expand in future versions to meet the needs specific to the US Realm.

  These requirements were originally developed, balloted, and published in FHIR DSTU2 as part of the Office of the National Coordinator for Health Information Technology (ONC) sponsored Data Access Framework (DAF) project. For more information on how DAF became US Core see the US Core change notes.

license: CC0-1.0
date: 2022-09-23
version: '6.0.0-ballot'
fhirVersion: 4.0.1
dependencies:
  hl7.fhir.uv.bulkdata: 2.0.0
  hl7.fhir.uv.smart-app-launch: 2.0.0
  us.nlm.vsac:
    uri: 'http://fhir.org/packages/us.nlm.vsac/ImplementationGuide/us.nlm.vsac'
    version: 0.7.0
    id: vsac
  hl7.fhir.uv.sdc: 3.0.0
  # hl7.fhir.us.sdoh-clinicalcare: 1.0.0
  us.cdc.phinvads:
    id: uscdcphinvads
    uri: 'http://fhir.org/packages/us.cdc.phinvads/ImplementationGuide/us.cdc.phinvads'
    version: 0.12.0
pages:
  index.md:
    title: Home
  conformance.md:
    general-requirements.md:
    must-support.md:
      observation-summary.md:
        title: Observation Summary Table
  guidance.md:
    uscdi.md:
      title: USCDI
    general-guidance.md:
    clinical-notes.md:
    medication-list.md:
    basic-provenance.md:
    screening-and-assessments.md:
      title:  Screening and Assessments
    changes-between-versions.md:
    future-of-US-core.md:
      title: Future of US Core
  profiles-and-extensions.md:
  capability-statements.md:
  search-parameters-and-operations.md:
  terminology.md:
  security.md:
  examples.md:
  downloads.md:
  changes.md:
    title: Change Log
  ImplementationGuide-hl7.fhir.us.core.md:
    title: US Core ImplementationGuide Resource
parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - input/resources
    - fsh-generated/resources
  path-pages:
    - input/pagecontent
    - input/intro-notes
    - fsh-generated/includes
    #- input/summaries
  path-expansion-params: '../../input/_resources/exp-params.json'  # for using US ed of SNOMED
  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'
  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'true'
  excludexml: 'false'
  excludejsn: 'false'
  excludettl: 'true'
  excludemap: 'true'
  excludeexample: 'true'
  suppressed-ids: '$examples'
  # generate: #what does this do - todo: remove and see
  #   - xml
  #   - json
  # no-narrative:
  #   - '*/*'  # does not seems to work
  #   - 'StructureDefinition/*'
  # no-validate:
  #   - '*/*'  # does not seems to work
  #   - 'StructureDefinition/*'
  version-comparison:
     - 5.0.1
     - 4.0.0
     - 3.1.1
copyrightyear: '2022+'
releaselabel: STU6 Ballot

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided ig-data/input/includes/menu.xml file, delete the "menu" property below.     │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Conformance: #conformance.html
      General Requirements: general-requirements.html
      Must Support: must-support.html
  Guidance: #guidance.html
      USCDI: uscdi.html
      General Guidance: general-guidance.html
      Clinical Notes: clinical-notes.html
      Medication List: medication-list.html
      Basic Provenance: basic-provenance.html
      Screening and Assessments: screening-and-assessments.html
      Changes Between Versions: changes-between-versions.html
      Future of US Core: future-of-US-core.html
  FHIR Artifacts: #artifact.html
      Profiles and Extensions: profiles-and-extensions.html
      Search Parameters and Operations: search-parameters-and-operations.html
      Terminology: terminology.html
      Capability Statements: capability-statements.html
  Security: security.html
  Examples: examples.html
  Downloads: downloads.html
  Change Log: changes.html
