resourceType: ValueSet
id: us-core-diagnosticreport-lab-codes
url: http://hl7.org/fhir/us/core/ValueSet/us-core-diagnosticreport-lab-codes
name: USCoreDiagnosticReportLabCodes
title: US Core Diagnostic Report Laboratory Codes
status: active
experimental: false
date: 2022-09-29
description: The Document Type value set includes all LOINC  values whose CLASSTYPE
  is LABORATORY in the LOINC database
copyright: "This material contains content from LOINC (http://loinc.org). LOINC is
  copyright \xA9 1995-2020, Regenstrief Institute, Inc. and the Logical Observation
  Identifiers Names and Codes (LOINC) Committee and is available at no cost under
  the license at http://loinc.org/license. LOINC\xAE is a registered United States
  trademark of Regenstrief Institute, Inc"
compose:
  include:
  - system: http://loinc.org
    filter:
    - property: CLASSTYPE
      op: '='
      value: '1'
