resourceType: ValueSet
id: us-core-screening-assessment-condition-category
url: http://hl7.org/fhir/us/core/ValueSet/us-core-screening-assessment-condition-category
name: USCoreScreeningAssessmentConditionCategory
title: US Core Screening Assessment Condition Category
status: active
experimental: false
date: 2023-04-05
description: Category codes used in the US Core Condition Screening Assessment Profile to help identify the type of USCDI Health Status/Assessment data class being reported.
copyright: Used by permission of HL7 International, all rights reserved Creative Commons
  License
compose:
  include:
  - system: http://hl7.org/fhir/us/core/CodeSystem/us-core-category

