resourceType: ValueSet
id: us-core-encounter-type
meta:
  versionId: '1'
  lastUpdated: '2022-04-27T23:40:04.892Z'
url: 'http://hl7.org/fhir/us/core/ValueSet/us-core-encounter-type'
version: 1.0.1
name: USCoreEncounterType
title: US Core Encounter Type
status: active
date: '2019-05-21'
publisher: HL7 US Realm Steering Committee
contact:
  - telecom:
      - system: other
        value: 'http://hl7.org/fhir'
description: >-
  The type of encounter: a specific code indicating type of service provided.
  This value set includes codes from SNOMED CT decending from the concept
  308335008 (Patient encounter procedure (procedure)) and codes from the Current
  Procedure and Terminology (CPT) found in the following CPT sections:

  - 99201-99499 E/M
  - 99500-99600 home health (mainly nonphysician, such as newborn care in home)
  - 99605-99607 medication management
  - 98966-98968 non physician telephone services

  (subscription to AMA Required)
copyright: >-
  1. This value set includes content from SNOMED CT, which is copyright © 2002+ International Health Terminology
  Standards Development Organisation (IHTSDO), and distributed by agreement
  between IHTSDO and HL7. Implementer use of SNOMED CT is not covered by this
  agreement.

  2. Current Procedural Terminology (CPT) is copyright 2020 American Medical Association. All rights reserved

compose:
  include:
    - system: 'http://snomed.info/sct'
      filter:
        - property: concept
          op: is-a
          value: '308335008'
    - system: 'http://www.ama-assn.org/go/cpt'
