resourceType: ValueSet
id: us-core-problem-or-health-concern
url: http://hl7.org/fhir/us/core/ValueSet/us-core-problem-or-health-concern
name: USCoreProblemOrHealthConcernValueSet
title: US Core Problem Or Health Concern ValueSet
status: active
date: '2022-04-12'
description: Code set for category codes for [US Core Condition Problems and Health Concerns Profile] consisting of the concepts "problem" and "health-concern".
compose:
  include:
    - system: http://terminology.hl7.org/CodeSystem/condition-category
      concept:
        - code: problem-list-item
    - system: http://hl7.org/fhir/us/core/CodeSystem/condition-category
      concept:
        - code: health-concern
